import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 950 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(900)
await pg.click('[data-testid="nav-reports"]'); await pg.waitForTimeout(600)
await pg.click('.rt-chart g:nth-child(2)'); await pg.waitForTimeout(400)
await pg.screenshot({ path: '.shots/c12-focus.png', clip: { x: 300, y: 130, width: 1290, height: 560 } })
// metric switch on attendance (has money column → real bars)
await pg.fill('[data-testid="rp-search"]', 'attendance'); await pg.waitForTimeout(200)
await pg.click('[data-testid="rp-def-attendance"]'); await pg.waitForTimeout(500)
await pg.click('[data-testid="rp-metric-charge"]'); await pg.waitForTimeout(400)
await pg.screenshot({ path: '.shots/c12-attend.png', clip: { x: 300, y: 130, width: 1290, height: 560 } })
// detail modal on a laptop-sized screen
await pg.setViewportSize({ width: 1180, height: 780 }); await pg.waitForTimeout(300)
await pg.click('[data-testid="nav-calendar"]'); await pg.waitForTimeout(500)
await pg.click('.tg-col .chip:not(.stack)'); await pg.waitForTimeout(400)
const m = await pg.evaluate(() => { const el = document.querySelector('.detail'); const b = el && el.querySelector('.body'); return el ? { w: Math.round(el.getBoundingClientRect().width), cols: getComputedStyle(b).gridTemplateColumns.split(' ').length, scroll: b.scrollHeight > b.clientHeight } : null })
console.log('detail@1180:', JSON.stringify(m))
await pg.screenshot({ path: '.shots/c12-detail-1180.png' })
await browser.close(); console.log('ok')
