import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 950 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1100)

await pg.click('[data-testid="nav-clients"]'); await pg.waitForTimeout(600)
await pg.screenshot({ path: '.shots/c16-clients-table.png' })
await pg.click('[data-testid="cli-mode-cards"]'); await pg.waitForTimeout(500)
await pg.screenshot({ path: '.shots/c16-clients-cards.png', clip: { x: 100, y: 130, width: 1500, height: 720 } })
await pg.click('[data-testid="cli-new"]'); await pg.waitForTimeout(500)
await pg.screenshot({ path: '.shots/c16-client-modal.png' })
await pg.keyboard.press('Escape'); await pg.waitForTimeout(200)
await pg.click('[data-testid="cli-mode-table"]')
await pg.click('[data-testid="cli-row-c1"]'); await pg.waitForTimeout(300)
await pg.click('[data-testid="cli-edit-c1"]'); await pg.waitForTimeout(400)
await pg.screenshot({ path: '.shots/c16-client-edit.png', clip: { x: 490, y: 130, width: 620, height: 700 } })
await pg.keyboard.press('Escape')
await pg.click('[data-testid="nav-staff"]'); await pg.waitForTimeout(500)
await pg.click('[data-testid="stf-mode-cards"]'); await pg.waitForTimeout(400)
await pg.screenshot({ path: '.shots/c16-staff-cards.png', clip: { x: 100, y: 130, width: 1500, height: 720 } })
await pg.click('[data-testid="stf-new"]'); await pg.waitForTimeout(450)
await pg.screenshot({ path: '.shots/c16-staff-modal.png', clip: { x: 490, y: 130, width: 620, height: 700 } })
// avatar picker close-up with hover + selection
await pg.click('[data-testid="sm-avatar-panda"]'); await pg.click('[data-testid="sm-avatar-fox"]'); await pg.waitForTimeout(200)
await pg.screenshot({ path: '.shots/c16-avatar-strip.png', clip: { x: 490, y: 130, width: 620, height: 330 } })
await browser.close(); console.log('shots done')
