import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 950 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
await pg.click('[data-testid="nav-clients"]'); await pg.waitForTimeout(500)
await pg.click('[data-testid="cli-new"]'); await pg.waitForTimeout(500)
await pg.screenshot({ path: '.shots/c16-modal-fixed.png', clip: { x: 490, y: 110, width: 620, height: 760 } })
// dark mode pass over the picker + cards
await pg.keyboard.press('Escape')
await pg.click('[data-testid="theme-toggle"]').catch(async () => { await pg.click('text=Theme'); })
await pg.waitForTimeout(400)
await pg.click('[data-testid="cli-mode-cards"]').catch(()=>{})
await pg.waitForTimeout(400)
await pg.screenshot({ path: '.shots/c16-dark-cards.png', clip: { x: 100, y: 100, width: 1500, height: 560 } })
await pg.click('[data-testid="cli-new"]').catch(()=>{})
await pg.waitForTimeout(450)
await pg.screenshot({ path: '.shots/c16-dark-modal.png', clip: { x: 490, y: 110, width: 620, height: 700 } })
await browser.close(); console.log('ok')
