import { chromium } from 'playwright-core'
let browser
try { browser = await chromium.launch() } catch {
  const { execSync } = await import('child_process')
  execSync('npx playwright-core install chromium-headless-shell', { stdio: 'inherit' })
  browser = await chromium.launch()
}
const pg = await browser.newPage({ viewport: { width: 1600, height: 950 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1100)
await pg.click('[data-testid="nav-clients"]'); await pg.waitForTimeout(500)
await pg.click('[data-testid="cli-open-c1"]'); await pg.waitForTimeout(450)
await pg.screenshot({ path: '.shots/c17-client-profile.png', clip: { x: 500, y: 100, width: 600, height: 740 } })
await pg.click('[data-testid="pf-edit"]'); await pg.waitForTimeout(350)
await pg.screenshot({ path: '.shots/c17-edit-from-profile.png', clip: { x: 500, y: 100, width: 600, height: 640 } })
await pg.keyboard.press('Escape'); await pg.waitForTimeout(150)
await pg.click('[data-testid="cli-mode-cards"]'); await pg.waitForTimeout(400)
await pg.screenshot({ path: '.shots/c17-cards-profile-btn.png', clip: { x: 100, y: 130, width: 1500, height: 340 } })
await pg.click('[data-testid="nav-staff"]'); await pg.waitForTimeout(400)
await pg.click('[data-testid="stf-open-s3"]'); await pg.waitForTimeout(400)
await pg.screenshot({ path: '.shots/c17-staff-profile.png', clip: { x: 500, y: 100, width: 600, height: 740 } })
await pg.keyboard.press('Escape')
await pg.click('[data-testid="nav-calendar"]'); await pg.waitForTimeout(600)
await pg.screenshot({ path: '.shots/c17-calendar-faces.png', clip: { x: 0, y: 0, width: 260, height: 950 } })
await browser.close(); console.log('ok')
