import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 980 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(700)
await pg.screenshot({ path: '.shots/c20-board2.png', clip: { x: 200, y: 180, width: 1390, height: 470 } })
await pg.click('[data-testid="dash-add"]'); await pg.waitForTimeout(300)
await pg.screenshot({ path: '.shots/c20-gallery2.png', clip: { x: 1000, y: 20, width: 600, height: 620 } })
await pg.click('[data-testid="dash-add"]')
await pg.click('[data-testid="dw-lg-service"]'); await pg.waitForTimeout(400)
await pg.screenshot({ path: '.shots/c20-filtered2.png', clip: { x: 200, y: 20, width: 1390, height: 660 } })
await browser.close(); console.log('ok')
