import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 980 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(700)

const clip = (w, sel) => pg.$eval(sel, (el) => ({ oh: el.offsetHeight, sh: el.scrollHeight }))
// 1. clipping checks (issues 2+3)
const dashSel = await pg.$eval('[data-testid="dash-range"]', (el) => { const r = el.getBoundingClientRect(); return { h: Math.round(r.height), clipped: el.scrollHeight > el.clientHeight + 1, fs: getComputedStyle(el).fontSize } })
await pg.click('[data-testid="nav-analytics"]'); await pg.waitForTimeout(500)
const anSel = await pg.$eval('[data-testid="an-metric"]', (el) => { const r = el.getBoundingClientRect(); return { h: Math.round(r.height), clipped: el.scrollHeight > el.clientHeight + 1, fs: getComputedStyle(el).fontSize } })
const anDim = await pg.$eval('[data-testid="an-dim"]', (el) => ({ clipped: el.scrollHeight > el.clientHeight + 1 }))
console.log('range:', JSON.stringify(dashSel), '| analytics metric:', JSON.stringify(anSel), 'dim clipped:', anDim.clipped)
await pg.screenshot({ path: '.shots/c21-an-controls.png', clip: { x: 210, y: 150, width: 700, height: 110 } })

// 2. drag-to-move: grab Mix header, drop after Bars
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(500)
const box = async (sel) => pg.$eval(sel, (el) => { const r = el.getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height } })
const mix = await box('[data-testid="dash-widget-w-mix"] .dsh-w-head')
const bars = await box('[data-testid="dash-widget-w-bars"]')
await pg.mouse.move(mix.x + mix.w / 2, mix.y + 10)
await pg.mouse.down()
await pg.mouse.move(bars.x + bars.w / 2, bars.y + bars.h / 2, { steps: 12 })
await pg.waitForTimeout(200)
// capture mid-drag ghost + indicator + (for resize later)
await pg.screenshot({ path: '.shots/c21-middrag.png', clip: { x: 200, y: 180, width: 1390, height: 640 } })
await pg.mouse.up(); await pg.waitForTimeout(400)
let order = await pg.evaluate(() => JSON.parse(localStorage.getItem('aloha-aba.v3')).dash.widgets.map((w) => w.id))
console.log('after move drag, order:', JSON.stringify(order))
// 3. resize: drag Mix's corner handle right by ~3 columns
const order0 = order
const mixNow = await box('[data-testid="dash-widget-' + order0.find((id) => id !== 'w-pulse' && id !== 'w-trend' && id !== 'w-heat') + '"]') // not robust — use mix explicitly
const m = await box('[data-testid="dash-widget-w-mix"]')
const before = await pg.$eval('[data-testid="dash-widget-w-mix"]', (el) => ({ w: Math.round(el.getBoundingClientRect().width), span: getComputedStyle(el).gridColumnEnd }))
await pg.mouse.move(m.x + m.w - 8, m.y + m.h - 8)
await pg.waitForTimeout(120)
await pg.hover('[data-testid="dash-widget-w-mix"]')
await pg.mouse.move(m.x + m.w - 8, m.y + m.h - 8)
await pg.mouse.down()
await pg.mouse.move(m.x + m.w - 8 + 620, m.y + m.h / 2, { steps: 14 })
await pg.waitForTimeout(150)
await pg.screenshot({ path: '.shots/c21-midsize.png', clip: { x: 200, y: 180, width: 1390, height: 640 } })
await pg.mouse.up(); await pg.waitForTimeout(400)
const after = await pg.$eval('[data-testid="dash-widget-w-mix"]', (el) => ({ w: Math.round(el.getBoundingClientRect().width), span: getComputedStyle(el).gridColumnEnd }))
const storedSpan = await pg.evaluate(() => JSON.parse(localStorage.getItem('aloha-aba.v3')).dash.widgets.find((w) => w.id === 'w-mix').span)
console.log('resize:', JSON.stringify(before), '->', JSON.stringify(after), 'stored span:', storedSpan)
await pg.screenshot({ path: '.shots/c21-after.png' })
// 4. reload persistence
await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(900)
const persist = await pg.evaluate(() => { const d = JSON.parse(localStorage.getItem('aloha-aba.v3')).dash; return { order: d.widgets.map((w) => w.id), spans: d.widgets.map((w) => w.span ?? null) } })
console.log('persisted:', JSON.stringify(persist))
// narrow reflow
await pg.setViewportSize({ width: 820, height: 1180 }); await pg.waitForTimeout(400)
await pg.screenshot({ path: '.shots/c21-narrow.png', clip: { x: 0, y: 60, width: 820, height: 760 } })
await browser.close(); console.log('DONE')
