import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 980 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(700)
const box = async (sel) => pg.$eval(sel, (el) => { const r = el.getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height } })
const mix = await box('[data-testid="dash-widget-w-mix"]')
const bars = await box('[data-testid="dash-widget-w-bars"]')
// start on the widget title (left part of header — a draggable zone), drop over the Bars card's left half → insert before Bars
await pg.mouse.move(mix.x + 16, mix.y + 14)
await pg.mouse.down()
await pg.mouse.move(bars.x + bars.w * 0.35, bars.y + bars.h / 2, { steps: 12 })
await pg.waitForTimeout(250)
await pg.screenshot({ path: '.shots/c21-middrag.png', clip: { x: 200, y: 60, width: 1390, height: 830 } })
await pg.mouse.up(); await pg.waitForTimeout(400)
const order = await pg.evaluate(() => JSON.parse(localStorage.getItem('aloha-aba.v3')).dash.widgets.map((w) => w.id))
console.log('move → order:', JSON.stringify(order))
// drag back: pulse after trend? and Escape-cancel test: start a drag and Esc
const pulse = await box('[data-testid="dash-widget-w-pulse"]')
const heat = await box('[data-testid="dash-widget-w-heat"]')
await pg.mouse.move(pulse.x + 16, pulse.y + 14)
await pg.mouse.down()
await pg.mouse.move(heat.x + heat.w / 2, heat.y + heat.h / 2, { steps: 10 })
await pg.waitForTimeout(200)
await pg.keyboard.press('Escape')
await pg.mouse.up(); await pg.waitForTimeout(300)
const order2 = await pg.evaluate(() => JSON.parse(localStorage.getItem('aloha-aba.v3')).dash.widgets.map((w) => w.id))
console.log('after Esc-cancel drag (must equal previous):', JSON.stringify(order2), JSON.stringify(order2) === JSON.stringify(order) ? 'CANCEL-OK' : 'CANCEL-FAIL')
await browser.close(); console.log('DONE')
