import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 980 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(700)
const box = async (sel) => pg.$eval(sel, (el) => { const r = el.getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height } })
const ord = () => pg.evaluate(() => JSON.parse(localStorage.getItem('aloha-aba.v3'))?.dash?.widgets?.map((w) => w.id) ?? null)
const mix = await box('[data-testid="dash-widget-w-mix"]')
const bars = await box('[data-testid="dash-widget-w-bars"]')
await pg.mouse.move(mix.x + 16, mix.y + 14)
await pg.mouse.down()
await pg.mouse.move(bars.x + bars.w * 0.68, bars.y + bars.h / 2, { steps: 12 })
await pg.waitForTimeout(220)
await pg.screenshot({ path: '.shots/c21-middrag2.png', clip: { x: 200, y: 60, width: 1390, height: 830 } })
await pg.mouse.up(); await pg.waitForTimeout(500)
console.log('move drop-after-bars →', JSON.stringify(await ord()))
// Escape cancels: move Pulse onto right half of Heat, press Esc, expect order unchanged
const cur = await ord()
const pulse = await box('[data-testid="dash-widget-w-pulse"]')
const heat = await box('[data-testid="dash-widget-w-heat"]')
await pg.mouse.move(pulse.x + 16, pulse.y + 14)
await pg.mouse.down()
await pg.mouse.move(heat.x + heat.w * 0.8, heat.y + heat.h / 2, { steps: 10 })
await pg.waitForTimeout(200)
await pg.keyboard.press('Escape')
await pg.mouse.up(); await pg.waitForTimeout(400)
const afterEsc = await ord()
console.log('after Esc:', JSON.stringify(afterEsc), JSON.stringify(afterEsc) === JSON.stringify(cur) ? 'CANCEL-OK' : 'CANCEL-FAIL')
await browser.close(); console.log('DONE')
