import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 980 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(700)
const box = async (sel) => pg.$eval(sel, (el) => { const r = el.getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height } })
// 1. menu opens over the Mix widget
await pg.hover('[data-testid="dash-widget-w-mix"]')
await pg.click('[data-testid="dw-more-w-mix"]'); await pg.waitForTimeout(350)
const heat0 = await box('[data-testid="dash-widget-w-heat"]')
await pg.screenshot({ path: '.shots/c22-menu.png', clip: { x: heat0.x - 250, y: 160, width: 560, height: 520 } })
console.log('menu open:', await pg.isVisible('[data-testid="dw-menu-w-mix"]'))
// click outside closes
await pg.mouse.click(400, 700); await pg.waitForTimeout(200)
console.log('menu closed on outside click:', !(await pg.isVisible('[data-testid="dw-menu-w-mix"]').catch(() => false)))
// 2. clone the trend widget + set Heat tall + Heat on new row
await pg.hover('[data-testid="dash-widget-w-trend"]')
await pg.click('[data-testid="dw-more-w-trend"]'); await pg.waitForTimeout(150)
await pg.click('[data-testid="dw-clone-w-trend"]'); await pg.waitForTimeout(400)
const cnt = await pg.$$eval('.dsh-w', (els) => els.length)
console.log('widgets after clone:', cnt)
const cloneId = await pg.evaluate(() => JSON.parse(localStorage.getItem('aloha-aba.v3')).dash.widgets[2].id)
// 3. two-axis corner resize on Heat: pull right (+2 cols) and down (+1 height step)
await pg.hover('[data-testid="dash-widget-w-heat"]')
const heat = await box('[data-testid="dash-widget-w-heat"]')
await pg.mouse.move(heat.x + heat.w - 8, heat.y + heat.h - 8)
await pg.mouse.down()
await pg.mouse.move(heat.x + heat.w + 380, heat.y + heat.h + 150, { steps: 14 })
await pg.waitForTimeout(150)
await pg.screenshot({ path: '.shots/c22-resize.png', clip: { x: 200, y: 160, width: 1390, height: 780 } })
await pg.mouse.up(); await pg.waitForTimeout(450)
const hs = await pg.evaluate(() => { const d = JSON.parse(localStorage.getItem('aloha-aba.v3')).dash; const w = d.widgets.find((x) => x.id === 'w-heat'); return { span: w.span, h: w.h } })
const heatAfter = await box('[data-testid="dash-widget-w-heat"]')
console.log('2-axis resize →', JSON.stringify(hs), 'px:', JSON.stringify({ w: Math.round(heatAfter.w), h: Math.round(heatAfter.h) }), '(was', Math.round(heat.w) + '×' + Math.round(heat.h) + ')')
// 4. new-row via menu on the trend clone; full width too
await pg.hover('[data-testid="dash-widget-' + cloneId + '"]')
await pg.click('[data-testid="dw-more-' + cloneId + '"]')
await pg.click('[data-testid="dw-newline-' + cloneId + '"]'); await pg.waitForTimeout(250)
await pg.hover('[data-testid="dash-widget-' + cloneId + '"]')
await pg.click('[data-testid="dw-more-' + cloneId + '"]')
await pg.click(`[data-testid="dw-size-${cloneId}-3"]`)
await pg.waitForTimeout(300)
const nlx = await pg.evaluate(() => { const d = JSON.parse(localStorage.getItem('aloha-aba.v3')).dash; const w = d.widgets.find((x) => x.id === 'w-clone') || d.widgets[2]; return { nl: w.nl } })
console.log('clone nl flag:', JSON.stringify(nlx))
await pg.screenshot({ path: '.shots/c22-final.png', clip: { x: 190, y: 40, width: 1400, height: 900 } })
// 5. persistence across reload
await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(900)
const persist = await pg.evaluate(() => { const d = JSON.parse(localStorage.getItem('aloha-aba.v3')).dash; return d.widgets.map((w) => `${w.id.slice(0, 7)}:${w.span ?? '-'}:${w.h ?? 1}${w.nl ? ':nl' : ''}`) })
console.log('persisted:', JSON.stringify(persist))
await browser.close(); console.log('DONE')
