import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 980 }, deviceScaleFactor: 1.5 })
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(900)
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(600)
const m = await pg.$eval('[data-testid="dash-widget-w-mix"]', (el) => { const r = el.getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height } })
await pg.hover('[data-testid="dash-widget-w-mix"]')
await pg.click('[data-testid="dw-more-w-mix"]'); await pg.waitForTimeout(250)
await pg.screenshot({ path: '.shots/c22-menu2.png', clip: { x: m.x - 40, y: m.y - 10, width: m.w + 70, height: 460 } })
await browser.close(); console.log('ok')
