import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 980 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
let downloadName = null, downloadText = null
pg.on('download', async (d) => { downloadName = d.suggestedFilename(); try { const fs = await import('fs'); const pth = '/tmp/dl.csv'; await d.saveAs(pth); downloadText = fs.readFileSync(pth, 'utf8').slice(0, 90) } catch (e) { console.log('dl read err', e.message) } })
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(600)
// 1. save board
await pg.click('[data-testid="dash-board-save"]'); await pg.waitForTimeout(200)
await pg.fill('[data-testid="dash-bname"]', 'Morning huddle')
await pg.keyboard.press('Enter'); await pg.waitForTimeout(350)
console.log('chip visible:', await pg.isVisible('text=Morning huddle'))
// 2. remove a widget, load board back
await pg.hover('[data-testid="dash-widget-w-bars"]'); await pg.click('[data-testid="dw-rm-w-bars"]'); await pg.waitForTimeout(350)
const n1 = await pg.$$eval('.dsh-w', (e) => e.length)
const chip = await pg.$eval('.dsh-bchip > button:first-child', (el) => el.textContent)
await pg.click(`[data-testid="dash-board-${await pg.evaluate(() => JSON.parse(localStorage.getItem('aloha-aba.v3')).dash.boards[0].id)}"]`)
await pg.waitForTimeout(350)
const n2 = await pg.$$eval('.dsh-w', (e) => e.length)
console.log(`widgets after remove:${n1} → board load:${n2} (chip "${chip}")`)
// 3. per-widget range override on trend: last13 → pill + more buckets in header
await pg.hover('[data-testid="dash-widget-w-trend"]')
await pg.click('[data-testid="dw-more-w-trend"]'); await pg.waitForTimeout(200)
await pg.selectOption('[data-testid="dw-range-w-trend"]', 'last13')
await pg.waitForTimeout(350)
const pillTxt = await pg.$eval('[data-testid="dw-rpill-w-trend"]', (el) => el.textContent)
const trendHead = await pg.$eval('[data-testid="dash-widget-w-trend"] .dw-plot-top span', (el) => el.textContent)
console.log('pill:', JSON.stringify(pillTxt), '| trend header:', JSON.stringify(trendHead))
await pg.screenshot({ path: '.shots/c23-pill.png', clip: { x: 200, y: 60, width: 1390, height: 480 } })
// open menu again for screenshot with range + CSV visible
await pg.hover('[data-testid="dash-widget-w-trend"]')
await pg.click('[data-testid="dw-more-w-trend"]'); await pg.waitForTimeout(200)
const tb = await pg.$eval('[data-testid="dw-menu-w-trend"]', (el) => { const r = el.getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height } })
await pg.screenshot({ path: '.shots/c23-menu.png', clip: { x: Math.max(0, tb.x - 20), y: Math.max(0, tb.y - 30), width: tb.w + 40, height: tb.h + 50 } })
await pg.keyboard.press('Escape')
// 4. CSV download through the real browser download pipeline
await pg.hover('[data-testid="dash-widget-w-bars"]')
await pg.click('[data-testid="dw-more-w-bars"]')
await pg.click('[data-testid="dw-csv-w-bars"]')
await pg.waitForTimeout(900)
console.log('download:', downloadName, '| head:', JSON.stringify(downloadText))
// 5. reload persistence + two-step board delete
await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(900)
const st = await pg.evaluate(() => { const d = JSON.parse(localStorage.getItem('aloha-aba.v3')).dash; return { boards: d.boards.map((b) => b.name), range: d.widgets.find((w) => w.id === 'w-trend')?.cfg?.range } })
console.log('persisted:', JSON.stringify(st))
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(400)
const bid = await pg.evaluate(() => JSON.parse(localStorage.getItem('aloha-aba.v3')).dash.boards[0].id)
await pg.click(`[data-testid="dash-board-del-${bid}"]`); await pg.waitForTimeout(150)
const armed = await pg.$eval(`[data-testid="dash-board-del-${bid}"]`, (el) => el.className)
await pg.screenshot({ path: '.shots/c23-armed.png', clip: { x: 200, y: 60, width: 900, height: 120 } })
await pg.click(`[data-testid="dash-board-del-${bid}"]`); await pg.waitForTimeout(350)
const boardsNow = await pg.evaluate(() => JSON.parse(localStorage.getItem('aloha-aba.v3')).dash.boards.length)
console.log('del armed class:', JSON.stringify(armed), '| boards after 2nd click:', boardsNow)
await browser.close(); console.log('DONE')
