import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 980 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(600)
const read = () => pg.$eval('[data-testid="dash-widget-w-trend"] .dw-plot-top', (el) => el.textContent.replace(/\s+/g, ' '))
console.log('global last4 :', await read())
await pg.hover('[data-testid="dash-widget-w-trend"]'); await pg.click('[data-testid="dw-more-w-trend"]')
await pg.selectOption('[data-testid="dw-range-w-trend"]', 'horizon')
await pg.waitForTimeout(400)
console.log('widget horizon :', await read())
await pg.hover('[data-testid="dash-widget-w-trend"]'); await pg.click('[data-testid="dw-rpill-w-trend"]'); await pg.waitForTimeout(300)
console.log('after clear    :', await read())
await browser.close(); console.log('ok')
