import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 980 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear()); await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
await pg.click('[data-testid="nav-settings"]'); await pg.waitForTimeout(500)
for (const k of ['program', 'location', 'service', 'staff']) { await pg.click(`[data-testid="set-extra-${k}"]`); await pg.waitForTimeout(120) }
const prev = await pg.$eval('[data-testid="set-name-preview"]', (el) => el.textContent.trim())
console.log('preview all-extras (chart):', JSON.stringify(prev))
await pg.screenshot({ path: '.shots/c25-settings.png', clip: { x: 320, y: 520, width: 700, height: 260 } })
await pg.click('[data-testid="set-name-code"]'); await pg.waitForTimeout(150)
console.log('preview code-first     :', JSON.stringify(await pg.$eval('[data-testid="set-name-preview"]', (el) => el.textContent.trim())))
await pg.click('[data-testid="set-name-ehr"]'); await pg.click('.set-modal .modal-x'); await pg.waitForTimeout(300)
// drawer with open buttons
await pg.click('[data-testid="nav-dashboard"]'); await pg.waitForTimeout(500)
await pg.click('[data-testid="dw-kpi-sessions"]'); await pg.waitForTimeout(400)
await pg.hover('.dd-roww'); await pg.waitForTimeout(150)
await pg.screenshot({ path: '.shots/c25-drawer.png', clip: { x: 1110, y: 0, width: 490, height: 640 } })
const openBtns = await pg.$$eval('.dd-open', (b) => b.length)
console.log('open buttons in drawer:', openBtns)
await pg.click('.dd-open'); await pg.waitForTimeout(400)
const card = await pg.$('[data-testid="detail-card"]')
console.log('detail card opened from dashboard:', !!card)
await pg.screenshot({ path: '.shots/c25-detail.png', clip: { x: 400, y: 60, width: 820, height: 620 } })
await pg.click('.detail .modal-x').catch(() => {}); await pg.waitForTimeout(250)
// new booking honors extras: quick-add → modal placeholder should include program/@ location/service line
const cols = await pg.$$('.tg-col')
await pg.click('[data-testid="nav-calendar"]'); await pg.waitForTimeout(400)
const cols2 = await pg.$$('.tg-col')
if (cols2.length) { const b = await cols2[2].boundingBox(); await pg.mouse.click(b.x + b.width / 2, b.y + 200) }
await pg.waitForTimeout(350)
await pg.click('[data-testid="type-service"]').catch(() => {})
await pg.waitForTimeout(350)
console.log('new-service placeholder:', JSON.stringify(await pg.$eval('[data-testid="appt-title"]', (el) => el.placeholder).catch(() => 'no modal')))
await browser.close(); console.log('DONE')
