import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const pg = await browser.newPage({ viewport: { width: 1600, height: 950 }, deviceScaleFactor: 1.5 })
pg.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await pg.evaluate(() => localStorage.clear())
await pg.reload({ waitUntil: 'networkidle' })
await pg.waitForTimeout(1200)
// jump to the crowded weekend anchor used in the complaint (Saturday demo block)
await pg.screenshot({ path: '.shots/c11-week.png', clip: { x: 60, y: 60, width: 1540, height: 860 } })
await pg.click('[data-testid="nav-reports"]')
await pg.waitForTimeout(700)
await pg.screenshot({ path: '.shots/c11-reports.png', clip: { x: 60, y: 60, width: 1540, height: 860 } })
// run a different report to show catalog + totals variety
await pg.click('[data-testid="rp-def-auth"]')
await pg.waitForTimeout(500)
await pg.screenshot({ path: '.shots/c11-reports-auth.png', clip: { x: 60, y: 60, width: 1540, height: 860 } })
// export toast check: click Excel
await pg.click('[data-testid="rp-xls"]')
await pg.waitForTimeout(500)
await pg.screenshot({ path: '.shots/c11-xls-toast.png', clip: { x: 400, y: 60, width: 1200, height: 300 } })
await browser.close()
console.log('shots done')
