import { chromium } from 'playwright-core'
const browser = await chromium.launch()
const errs = []
async function shot(w, h, name, steps) {
  const pg = await browser.newPage({ viewport: { width: w, height: h }, deviceScaleFactor: 1.5 })
  pg.on('pageerror', (e) => errs.push('PAGEERROR: ' + e.message))
  pg.on('console', (m) => { if (m.type() === 'error') errs.push('CONSOLE: ' + m.text()) })
  await pg.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
  await pg.evaluate(() => localStorage.clear())
  await pg.reload({ waitUntil: 'networkidle' }); await pg.waitForTimeout(700)
  const colw = () => pg.evaluate(() => Math.round(document.querySelector('.tg-dayhead')?.getBoundingClientRect().width || 0))
  const railCollapsed = () => pg.evaluate(() => document.querySelector('.navrail').classList.contains('collapsed'))
  console.log(`\n== ${name} (${w}×${h}) ==`)
  if (steps) await steps(pg)
  console.log('day col px:', await colw(), '| rail collapsed:', await railCollapsed())
  await pg.screenshot({ path: `.shots/ux-${name}.png` })
  await pg.close()
}
await shot(1440, 860, 'default', async (pg) => {})
await shot(1440, 860, 'hidden-filters', (pg) => pg.getByTestId('sb-collapse').click().then(() => pg.waitForTimeout(400)))
await shot(1440, 860, 'rail-expanded', (pg) => pg.getByTestId('nav-collapse').click().then(() => pg.waitForTimeout(400)))
await shot(1080, 780, 'narrow', async (pg) => { console.log('ghost visible:', await pg.getByTestId('sb-expand').isVisible()) })
await shot(1440, 860, 'billing-stays-expanded', async (pg) => {
  await pg.getByTestId('nav-billing').click(); await pg.waitForTimeout(600)
  console.log('rail collapsed on billing (want false):', await (() => pg.evaluate(() => document.querySelector('.navrail').classList.contains('collapsed')))())
  await pg.getByTestId('nav-calendar').click(); await pg.waitForTimeout(500)
  console.log('rail collapsed back on calendar (want true):', await (() => pg.evaluate(() => document.querySelector('.navrail').classList.contains('collapsed')))())
})
console.log('\nERRORS:', errs.length ? errs.join('; ') : 'none')
await browser.close()
